language: java
sudo: false
dist: trusty

stages:
  - checkstyle
  - test
  - Integration Test
  - Deploy Snapshot

jdk:
  - oraclejdk9
  - oraclejdk8
  - openjdk7

matrix:
  include:
  - stage: Integration Test
    jdk: openjdk7
    env: CUSTOM_MVN_VERION="3.0"
  - jdk: openjdk7
    env: CUSTOM_MVN_VERION="3.0.5"
  - jdk: openjdk7
    env: CUSTOM_MVN_VERION="3.1.1"
  - jdk: openjdk7
    env: CUSTOM_MVN_VERION="3.2.5"
  - jdk: openjdk7
    env: CUSTOM_MVN_VERION="3.3.9"
  - jdk: oraclejdk9
    env: CUSTOM_MVN_VERION="3.5.0"
  - jdk: oraclejdk9
    env: CUSTOM_MVN_VERION="3.5.2"
  - stage: checkstyle
    jdk: oraclejdk9
    script: mvn clean verify -Pcheckstyle -Dcheckstyle.version=8.2 -Dmaven.test.skip=true -B
    env: CHECKSTYLE=8.2
  - stage: checkstyle
    jdk: openjdk7
    script: mvn clean verify -Pcheckstyle -Dmaven.test.skip=true -B
    env: CHECKSTYLE=6.11.2
  - stage: Deploy Snapshot
    env:
      - secure: "n595+AgD94KxAeH0sR252iy5WejibJOmp+S6gkvaZHzw20U7wxZha6Qc2KuvQ9M+b6VR9cddIz+kVMHFNaauumbKg4EbvYXXWzNZeitUXiuck2hphMqBaf3delciDeVdjukgdbw1h/IRQLD4RIGPZ2hvE5lik/Ruo7jxRf2N1tFIeep3x3OtiUSCaLNwNaG8CNNyuk9NFAMQ8/oC54RBFbzQLUI3x3lKDM2mrRE2cvmeIO+1J4xK34O87QrFsNawqZR9GeaSIFHEDrezQyv9rOC7m+1es7fky7zY+ikTw9I+LMPl1L0LtPaRbbANQpogCQLPKwXjcRB3zDzGLnwFuEIKugTwM3HDG6EVkl2/sQDwCKjMuNFQtNoPHycM1sk72gYe9v3j+t1OS5tZljXBhzatmsdUsklg/+kPm6uxEen08JdARslcpIxq2PoivmYT/YKnjL47Ig4pOMi++x/b35JzptTdfVlR7dkoDSwU9p1/EpoR1blZF5KI+Kzz9YlNKBfoa6acX2Bk458M8PyIwOgN8mSJGT+Y/WdvtxBCblS8NOdLDaz2U9K4pRZYTmdiMX6ZQt/mQdkPZ+/4rqCjj7EILwWmw9kMOWS1///Pmhn4PQw8eaRWBWBzd1ZlRHY/qH03sGUDAUuiEcJkMYVaVi49VmHlQ8qF49RpVFyEuJ0="
      - secure: "zPnvKX9QK1+SokxVp1rVedIX23ftTHMOGMrGNzzhyyR2W2DTeFnTjOKShMc6FNmO827O6pkbiv6VJahH7dYCltf63GYu/+pl570uBjgdvslwNSBMSwLbJpxJyRv5g/IRGoSbyXpSG6aPPA8lp46UBZUm+C+0Z6IBWPlNjMjjtPE6htl+d6yt9eddA+dbK3UiUkz+kT4csva/aArWUsKlpzfALazPrewpa2MxwyYWeC1QoAIt7qUkNtvuIRXbT5gVJ6mTZayRx8V7fDDvHPaB3PHWuiobk8IpLKMolVLZpOeaOVJXnMh0c6xSQxdEB7WPVB0SGGN5sQ7IwJeneSlZkr95dH8CWRkb7r9cTCM2QnHjR/AU6Z2vx9kKK5BiaQNqnT1mRe3fPp1MkIKFtadX0exzLr2XdsDZw1kBVP1V4Z+WlHiikFStbwJlZ3DqPf6Uen405MM8/2zD+2Q758P37mRV/6VmT7xLXGJAa5Pc/ySlJHi4zbciED0pdMWhZ1GHf6OXexlJeprRaUKtUu5PROujiqkQZzGJHLIFNwQ+r54N/SpPAUgx62bHrBmgVPemGeAKFUs/uAr9agJdl+9IhwGHceRew3RTsmOMrQYDtZ3DFW2UkOZ2X+ssuEEyUNNOiZ+d4khgDFVO00aeo1tRt3KQNcQzs1IAVAgUG6G5Mg0="
    script: mvn clean deploy --settings=".buildscript/settings.xml"

install:
  - if [[ -n "${CUSTOM_MVN_VERION}" ]]; then
      echo "Download Maven ${CUSTOM_MVN_VERION}....";
      if [[ "${CUSTOM_MVN_VERION}" == "3.0" ]]; then
        wget https://archive.apache.org/dist/maven/binaries/apache-maven-3.0-bin.zip || travis_terminate 1;
      else
        wget https://archive.apache.org/dist/maven/maven-3/${CUSTOM_MVN_VERION}/binaries/apache-maven-${CUSTOM_MVN_VERION}-bin.zip || travis_terminate 1;
      fi;
      unzip -qq apache-maven-${CUSTOM_MVN_VERION}-bin.zip || travis_terminate 1;
      export M2_HOME=$PWD/apache-maven-${CUSTOM_MVN_VERION};
      export PATH=$M2_HOME/bin:$PATH;
      mvn -version;
    fi

script:
  - mvn clean test install -B
  - mvn clean initialize -Pdemo -Dmaven.test.skip=true -B
  - /bin/bash -c '[[ -f target/testing.properties ]] && cat target/testing.properties || travis_terminate 1;'
